# Generated by Django 6.0 on 2025-12-09 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mingos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='reserved_stock_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('ORDER_PLACED', 'Order Placed - Reserved'), ('ORDER_COMPLETED', 'Order Completed - Deducted'), ('ORDER_CANCELLED', 'Order Cancelled - Released'), ('PURCHASE_RECEIVED', 'Purchase Order Received'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mingos.ingredient')),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mingos.customerorder')),
                ('reference_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mingos.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
