# Generated by Django 6.0 on 2025-12-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mingos', '0002_ingredient_reserved_stock_qty_inventorytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='reserved_stock_qty',
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
    ]
